applications:
  ctix:
    base_url: "CTIX url"
    # Example URL : "https://demo.ctix.cyware.com/"
    auth:
      type: "basic"
      username: "username"
      password: "password"
      # type: "token"
      # token: "token(The token can be obtained from the Authorization header of any API call of the product)"
  co:
    base_url: "CO url"
    # Example URL : "https://demo.ctix.cyware.com/"
    auth:
      type: "basic"
      username: "username"
      password: "password"
      # type: "token"
      # token: "token(The token can be obtained from the Authorization header of any API call of the product)"
server:
  mcp_mode: "stdio"
  # port: "5421"
