applications:
  ctix:
    base_url: "ctix base url"
    auth:
      type: "basic"
      username: "ctix user name"
      password: "ctix password"
      # type: "token"
      # token: "Your token""


server:
  mcp_mode: "stdio"
  # port: "5421"
